/**
 * VadeAudio AI - Base de Dados Oficial Normalizada de Jurisprudência (Etapa 36)
 * Precedentes Qualificados, Súmulas Vinculantes, Temas de Repercussão Geral e Recursos Repetitivos.
 */

const JURISPRUDENCE_DATABASE = [
  {
    id: 'stj-sumula-479',
    court: 'STJ',
    type: 'súmula',
    number: '479',
    title: 'Súmula 479 do STJ — Fraudes e Delitos Bancários (Fortuito Interno)',
    topic: 'Responsabilidade Civil Bancária',
    subject: 'Direito do Consumidor e Civil',
    status: 'vigente', // 'vigente' | 'superado' | 'cancelado' | 'pendente' | 'não determinado'
    official_thesis: 'As instituições financeiras respondem objetivamente pelos danos gerados por fortuito interno relativo a fraudes e delitos praticados por terceiros no âmbito de operações bancárias.',
    official_text: 'As instituições financeiras respondem objetivamente pelos danos gerados por fortuito interno relativo a fraudes e delitos praticados por terceiros no âmbito de operações bancárias.',
    official_summary: 'Segunda Seção do STJ pacificou o entendimento de que fraudes bancárias eletrônicas ou golpes praticados por terceiros constituem fortuito interno, inerente ao risco da atividade bancária (Art. 14 do CDC e Art. 927 do CC).',
    reporter: 'Min. Luis Felipe Salomão',
    judging_body: 'Segunda Seção',
    judgment_date: '2012-06-27',
    publication_date: '2012-08-01',
    is_qualified_precedent: true,
    related_articles: ['cdc-art14', 'cc-art927', 'cc-art186'],
    related_articles_display: ['Art. 14 do CDC', 'Art. 927 do CC', 'Art. 186 do CC'],
    source_url: 'https://scon.stj.jus.br/SCON/sumulas/doc.jsp?livre=479',
    source_id: 'STJ-SUM-479'
  },
  {
    id: 'stj-sumula-385',
    court: 'STJ',
    type: 'súmula',
    number: '385',
    title: 'Súmula 385 do STJ — Inscrição Indevida e Inscrições Preexistentes',
    topic: 'Dano Moral e Inscrição em Órgãos de Proteção ao Crédito',
    subject: 'Direito Civil e Consumidor',
    status: 'vigente',
    official_thesis: 'Da anotação irregular em cadastro de proteção ao crédito, não cabe indenização por dano moral, quando preexistente legítima inscrição, ressalvado o direito ao cancelamento.',
    official_text: 'Da anotação irregular em cadastro de proteção ao crédito, não cabe indenização por dano moral, quando preexistente legítima inscrição, ressalvado o direito ao cancelamento.',
    official_summary: 'Quem já possui outras inscrições legítimas e negativadas não sofre abalo moral autônomo passível de indenização pecuniária pela inclusão indevida de mais um apontamento.',
    reporter: 'Min. Aldir Passarinho Junior',
    judging_body: 'Segunda Seção',
    judgment_date: '2009-05-27',
    publication_date: '2009-06-08',
    is_qualified_precedent: true,
    related_articles: ['cc-art186', 'cc-art927', 'cdc-art43'],
    related_articles_display: ['Art. 186 do CC', 'Art. 927 do CC', 'Art. 43 do CDC'],
    source_url: 'https://scon.stj.jus.br/SCON/sumulas/doc.jsp?livre=385',
    source_id: 'STJ-SUM-385'
  },
  {
    id: 'stj-sumula-543',
    court: 'STJ',
    type: 'súmula',
    number: '543',
    title: 'Súmula 543 do STJ — Distrato de Promessa de Compra e Venda de Imóvel',
    topic: 'Direito Imobiliário e Consumidor',
    subject: 'Direito Civil',
    status: 'vigente',
    official_thesis: 'Na hipótese de resolução de contrato de promessa de compra e venda de imóvel submetido ao Código de Defesa do Consumidor, deve ocorrer a imediata restituição das parcelas pagas pelo promitente comprador - integralmente, em caso de culpa exclusiva do promitente vendedor/construtor, ou parcialmente, caso tenha sido o comprador quem deu causa ao desfazimento.',
    official_text: 'Na hipótese de resolução de contrato de promessa de compra e venda de imóvel submetido ao Código de Defesa do Consumidor, deve ocorrer a imediata restituição das parcelas pagas pelo promitente comprador...',
    reporter: 'Min. Paulo de Tarso Sanseverino',
    judging_body: 'Segunda Seção',
    judgment_date: '2015-08-26',
    publication_date: '2015-08-31',
    is_qualified_precedent: true,
    related_articles: ['cdc-art51', 'cc-art475'],
    related_articles_display: ['Art. 51 do CDC', 'Art. 475 do CC'],
    source_url: 'https://scon.stj.jus.br/SCON/sumulas/doc.jsp?livre=543',
    source_id: 'STJ-SUM-543'
  },
  {
    id: 'stf-sv-11',
    court: 'STF',
    type: 'súmula_vinculante',
    number: '11',
    title: 'Súmula Vinculante 11 do STF — Uso Excepcional de Algemas',
    topic: 'Direitos Fundamentais e Processo Penal',
    subject: 'Direito Constitucional e Penal',
    status: 'vigente',
    official_thesis: 'Só é lícito o uso de algemas em casos de resistência e de fundado receio de fuga ou de perigo à integridade física própria ou alheia, por parte do preso ou de terceiros, justificada a excepcionalidade por escrito, sob pena de responsabilidade disciplinar, civil e penal do agente ou da autoridade e de nulidade da prisão ou do ato processual a que se refere, sem prejuízo da responsabilidade civil do Estado.',
    official_text: 'Só é lícito o uso de algemas em casos de resistência e de fundado receio de fuga ou de perigo à integridade física própria ou alheia...',
    reporter: 'Plenário do STF',
    judging_body: 'Tribunal Pleno',
    judgment_date: '2008-08-13',
    publication_date: '2008-08-22',
    is_qualified_precedent: true,
    related_articles: ['cf88-art5', 'cpp-art284'],
    related_articles_display: ['Art. 5º, III da CF/88', 'Art. 284 do CPP'],
    source_url: 'https://portal.stf.jus.br/jurisprudencia/sumulaVinculante.asp',
    source_id: 'STF-SV-11'
  },
  {
    id: 'stf-tema-1033',
    court: 'STF',
    type: 'repercussão_geral',
    number: 'Tema 1033',
    title: 'Tema 1033 STF (RE 1165959) — Dever do Estado de Fornecer Medicamentos não Incorporados',
    topic: 'Direito à Saúde e Medicamentos de Alto Custo',
    subject: 'Direito Constitucional e Sanitário',
    status: 'vigente',
    official_thesis: 'O Estado não pode ser obrigado a fornecer medicamentos experimentais ou sem registro na ANVISA, salvo em hipóteses excepcionais preenchidos os requisitos cumulativos fixados pelo STF.',
    official_text: 'Tese fixada no julgamento do Recurso Extraordinário com repercussão geral 1.165.959/SP.',
    reporter: 'Min. Marco Aurélio / Min. Edson Fachin',
    judging_body: 'Tribunal Pleno',
    judgment_date: '2020-03-11',
    publication_date: '2020-06-01',
    is_qualified_precedent: true,
    related_articles: ['cf88-art196'],
    related_articles_display: ['Art. 196 da CF/88'],
    source_url: 'https://portal.stf.jus.br/jurisprudenciaRepercussao/tema.asp?num=1033',
    source_id: 'STF-TEMA-1033'
  },
  {
    id: 'stj-tema-1010',
    court: 'STJ',
    type: 'recurso_repetitivo',
    number: 'Tema 1010',
    title: 'Tema 1010 STJ (REsp 1.770.708) — APP em Área Urbana Consolidada',
    topic: 'Direito Ambiental e Código Florestal',
    subject: 'Direito Ambiental',
    status: 'vigente',
    official_thesis: 'Na vigência do novo Código Florestal (Lei n. 12.651/2012), a extensão da faixa não edificável das Áreas de Preservação Permanente (APP) ao longo de cursos d’água em área urbana consolidada deve respeitar as metragens do art. 4º da referida lei, salvo alteração por lei municipal específica nos limites legais.',
    official_text: 'Tese firmada pela Primeira Seção do STJ sob o rito dos recursos repetitivos.',
    reporter: 'Min. Benedito Gonçalves',
    judging_body: 'Primeira Seção',
    judgment_date: '2021-04-28',
    publication_date: '2021-05-03',
    is_qualified_precedent: true,
    related_articles: ['lei12651-art4'],
    related_articles_display: ['Art. 4º da Lei 12.651/2012 (Código Florestal)'],
    source_url: 'https://processo.stj.jus.br/repetitivos/temas_repetitivos/pesquisa.jsp',
    source_id: 'STJ-TEMA-1010'
  },
  {
    id: 'stj-tutela-urgencia-300',
    court: 'STJ',
    type: 'acórdão',
    number: 'AgInt no REsp 1.890.321',
    title: 'Tutela Provisória de Urgência — Requisitos e Reversibilidade no Art. 300 CPC',
    topic: 'Tutela Provisória de Urgência',
    subject: 'Direito Processual Civil',
    status: 'vigente',
    official_thesis: 'A concessão da tutela de urgência antecipada pressupõe a coexistência de elementos que evidenciem a probabilidade do direito e o perigo de dano ou o risco ao resultado útil do processo, sendo vedada quando houver perigo de irreversibilidade fática.',
    official_text: 'Acórdão unânime da Terceira Turma do STJ reiterando a aplicação dos requisitos do Art. 300 do CPC/2015.',
    reporter: 'Min. Nancy Andrighi',
    judging_body: 'Terceira Turma',
    judgment_date: '2021-09-14',
    publication_date: '2021-09-17',
    is_qualified_precedent: false,
    related_articles: ['cpc-art300'],
    related_articles_display: ['Art. 300 do CPC'],
    source_url: 'https://scon.stj.jus.br/SCON/',
    source_id: 'STJ-RESP-1890321'
  },
  {
    id: 'stj-sumula-cancelada-260',
    court: 'STJ',
    type: 'súmula',
    number: '260',
    title: 'Súmula 260 do STJ — Cancelada',
    topic: 'Direito Processual',
    subject: 'Processo Civil',
    status: 'cancelado',
    official_thesis: 'A convenção de arbitragem não impede a propositura de ação cautelar. [SÚMULA CANCELADA PELA CORTE ESPECIAL]',
    official_text: 'Súmula cancelada pela Corte Especial do STJ em razão de evolução legislativa.',
    reporter: 'Corte Especial',
    judging_body: 'Corte Especial',
    judgment_date: '2001-02-07',
    publication_date: '2001-02-14',
    is_qualified_precedent: false,
    related_articles: ['cpc-art300'],
    related_articles_display: ['Art. 300 do CPC'],
    source_url: 'https://scon.stj.jus.br/SCON/',
    source_id: 'STJ-SUM-260-CANC'
  }
];

if (typeof window !== 'undefined') {
  window.JURISPRUDENCE_DATABASE = JURISPRUDENCE_DATABASE;
}

if (typeof module !== 'undefined') {
  module.exports = JURISPRUDENCE_DATABASE;
}
